config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
  resources :cat_rental_requests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = %w(black white brown red blue)
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: ['M', 'F'] }
  validates :color, inclusion: { in: COLORS }


  has_many :rental_requests, dependent: :destroy,
    class_name: :CatRentalRequest,
    primary_key: :id,
    foreign_key: :cat_id

  def age
    time_ago_in_words(birth_date)
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING) }
  validates :cat_id, :start_date, :end_date, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    class_name: :Cat,
    primary_key: :id,
    foreign_key: :cat_id

  def overlapping_requests
  cat.rental_requests
          .where.not(id: self.id)
          .where.not('end_date < ?', start_date)
          .where.not('start_date > ?', end_date)

  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_request
    !overlapping_approved_requests.exists?
  end

  def approve!
    if self.does_not_overlap_approved_request
      self.status = 'APPROVED'
      ActiveRecord::Base.transaction do
        self.save
        self.overlapping_requests.each do |request|
          request.status = 'DENIED'
          request.save
        end
      end
    else
      'Unable to approve request - Conflicting approved request'
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    render :new
  end

  def create
    @rental_request = CatRentalRequest.new(rental_request_params)

    if @rental_request.save
      redirect_to cat_url(@rental_request.cat_id)
    else
      render json: @rental_requests.errors.full_messages
    end
  end


  def rental_request_params
    params.require(:cat_rental_requests).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat
      render :show
    else
      render json: 'cat does not exist', status: 404
    end
  end

  def new
    @cat = Cat.new
    render :new 
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  private
  def cat_params
    params.require(:cats).permit(:name, :sex, :birth_date, :description, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<form action=" <%= cat_rental_requests_url %> " method="post">

<label for="cat">Select a Cat: </label>
<select id="cat" name="cat_rental_requests[cat_id]">
  <option disabled selected>--Please Select--</option>
  <% @cats.each do |cat| %>
  <option value="<%= cat.id %>"><%= cat.name %></option>
  <% end %>
</select>

<br>

<label for="start_date">Start Date: </label>
<input id="start_date" type="date" name="cat_rental_requests[start_date]" value="">

<br>

<label for="end_date">End Date: </label>
<input id="end_date" type="date" name="cat_rental_requests[end_date]" value="">

<br>

<input type="submit" value="Add Reservation">

</form>

app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action= "<%= action_url %>" method="post">
  <% if cat.persisted?%>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name:</label>
  <input id="name" type="text" name="cats[name]" value=" <%= cat.name %> ">

  <br>

  <label for="sex">Sex: </label>
  <input type="radio" name="cats[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %> > Male
  <input type="radio" name="cats[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %> > Female

  <br>
  <label for="color">Color: </label>
  <select id="color" name="cats[color]">
    <option disabled <%= cat.color ? "" : "selected"  %> >--Please Select--</option>
    <option value="black" <%= cat.color == "black" ? "selected" : "" %>>Black</option>
    <option value="white"<%= cat.color == "white" ? "selected" : "" %> >White</option>
    <option value="brown" <%= cat.color == "brown" ? "selected" : "" %> >Brown</option>
    <option value="red" <%= cat.color == "red" ? "selected" : "" %> >Red</option>
    <option value="blue" <%= cat.color == "blue" ? "selected" : "" %> >Blue</option>
  </select>
  <br>
  <label for="date">Date: </label>
  <input type="date" name="cats[birth_date]" value="<%= cat.birth_date ? cat.birth_date.strftime('%Y-%m-%d') : "" %>">
  <br><br>
  <label for="description">Description: </label><br>
  <textarea name="cats[description]" rows="8" cols="80"><%=cat.description%></textarea>
  <input type="submit" value="<%= action == :edit ? 'update cat' : 'add cat'%>">
</form>

app/views/cats/edit.html.erb
<h1>Update cat!</h1>

<%= render 'form', action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <!-- <li><%#= "#{cat.name} #{cat.id}" %></li> -->
  <li> <%= link_to [cat.name, cat.id], cat_url(cat) %> </li>
<% end %>

app/views/cats/new.html.erb
<h1>Add cat!</h1>

<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td> <%= @cat.name %> </td>
    <td> <%= @cat.birth_date %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.description %> </td>
    <td> <%=  %> </td>

  </tr>
</table>
  <br><br>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>
    <% @cat.rental_requests.each do |request| %>
    <tr>
      <td> <%= request.start_date %> </td>
      <td> <%= request.end_date %> </td>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>